export const industryMeta = {
  manufacturing: { title: "Manufacturing Intelligence", subtitle: "Industrial automation, supply chain, smart factory signals", icon: "cog" },
  automotive:    { title: "Automotive Intelligence", subtitle: "EV transition, autonomous driving, mobility ecosystem signals", icon: "car" },
  pharma:        { title: "Pharma & Life Sciences Intelligence", subtitle: "Drug discovery, clinical trials, regulatory pipeline signals", icon: "flask-conical" },
  energy:        { title: "Energy & Utilities Intelligence", subtitle: "Clean energy transition, grid modernization, carbon market signals", icon: "zap" },
  finance:       { title: "Banking & Finance Intelligence", subtitle: "Digital banking, regulatory compliance, fintech disruption signals", icon: "landmark" },
  investment:    { title: "Investment Banking Intelligence", subtitle: "M&A pipeline, capital markets, deal flow and advisory signals", icon: "trending-up" },
  defense:       { title: "Defense & Aerospace Intelligence", subtitle: "Procurement, autonomous systems, geopolitical risk signals", icon: "shield" },
  telecom:       { title: "Telecom Intelligence", subtitle: "5G/6G infrastructure, Open RAN, satellite convergence signals", icon: "radio-tower" },
};

export const industryData = {
  manufacturing: {
    label: "SECTOR: MANUFACTURING", sources: "1,247 sources",
    stats: { signals: "342", signalsDelta: "▲ 18%", alerts: "7", alertsDelta: "▲ 3", competitors: "12", compDelta: "2 active", confidence: "97.8%" },
    chartTag: "Industrial Automation", chartLeg1: "Market Size", chartVal: "$847B", chartDelta: "▲ 14.2%",
    insightTitle: "Automation Spend Accelerating",
    insightDesc: "Industrial automation investments up 14.2% YoY, driven by labor shortages and reshoring. Robotics & IIoT leading adoption — smart factory deployments accelerating in APAC and Europe.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "2h ago", title: "Siemens announces AI-native factory OS — direct competitor to smart manufacturing stack", desc: "Platform integrates digital twin, predictive maintenance, and autonomous quality control. Market share impact assessed at 12-18% in industrial automation segment.", tags: ["Competitor", "Market Impact", "Product Launch"] },
      { level: "MEDIUM", lvlClass: "amber", time: "5h ago", title: "EU Carbon Border Adjustment Mechanism Phase 2 finalized", desc: "New carbon reporting requirements for all imported manufactured goods effective Q3 2025. Compliance cost impact estimated at 3-7% of input costs.", tags: ["Regulatory", "Supply Chain", "Opportunity"] },
      { level: "INNOVATION", lvlClass: "emerald", time: "8h ago", title: "MIT breakthrough in cobalt-free battery chemistry — production cost impact", desc: "New cathode material achieves 95% energy density of LiCoO₂ at 40% lower cost. Commercialization timeline: 18-24 months.", tags: ["Technology", "R&D"] },
    ],
    heatmap: [
      { label: "Robotics", val: "+22%", color: "rgba(16,185,129,0.25)" }, { label: "IIoT", val: "+18%", color: "rgba(16,185,129,0.18)" },
      { label: "Digital Twin", val: "+15%", color: "rgba(6,182,212,0.15)" }, { label: "Additive Mfg", val: "+9%", color: "rgba(139,92,246,0.12)" },
      { label: "Supply Chain", val: "+7%", color: "rgba(245,158,11,0.12)" }, { label: "Raw Materials", val: "-3%", color: "rgba(239,68,68,0.08)" },
      { label: "Sustainability", val: "+12%", color: "rgba(16,185,129,0.1)" }, { label: "QA/Testing", val: "+5%", color: "rgba(6,182,212,0.08)" },
    ],
    competitors: [
      { init: "S", name: "Siemens", evt: "Platform launch", lvl: "High", lvlClass: "red" },
      { init: "A", name: "ABB", evt: "Acquisition rumor", lvl: "Med", lvlClass: "amber" },
      { init: "H", name: "Honeywell", evt: "Earnings beat", lvl: "Low", lvlClass: "blue" },
    ],
    radarCount: "Tracking 12",
    metrics: [
      { label: "Market Size", val: "$847B", color: "text-white" }, { label: "CAGR (5Y)", val: "14.2%", color: "text-emerald-400" },
      { label: "M&A Volume", val: "$32.4B", color: "text-cyan-400" }, { label: "Patent Filings", val: "4,821", color: "text-violet-400" },
    ],
    activity: [
      { title: "Sector scan completed", detail: "1,247 sources • 42 insights" },
      { title: "Executive brief generated", detail: "Q4 Competitive Landscape" },
      { title: "Priority signal detected", detail: "Siemens platform launch" },
    ],
  },
  automotive: {
    label: "SECTOR: AUTOMOTIVE", sources: "2,184 sources",
    stats: { signals: "518", signalsDelta: "▲ 24%", alerts: "11", alertsDelta: "▲ 5", competitors: "18", compDelta: "4 active", confidence: "96.9%" },
    chartTag: "EV & Autonomous Vehicles", chartLeg1: "Market Size", chartVal: "$1.2T", chartDelta: "▲ 22.8%",
    insightTitle: "EV Transition Accelerating Globally",
    insightDesc: "Global EV market share surpassed 20% in Q3. Chinese OEMs gaining 8% European market share QoQ. Battery costs declining 18% YoY, enabling sub-$25K EV segments.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "1h ago", title: "BYD surpasses Toyota in quarterly revenue for first time — landmark shift", desc: "Revenue of $52.8B driven by aggressive pricing and vertical integration. European tariff response expected within 30 days.", tags: ["Competitor", "Market Shift", "Revenue"] },
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "3h ago", title: "NHTSA proposes Level 4 autonomous vehicle certification framework", desc: "Regulatory milestone enabling commercial autonomous deployment. Waymo, Cruise, and Tesla positioned to benefit. Compliance timeline Q2 2026.", tags: ["Regulatory", "Autonomous", "Framework"] },
      { level: "MEDIUM", lvlClass: "amber", time: "6h ago", title: "Solid-state battery pilot production begins at Toyota & Samsung SDI", desc: "First 1GWh pilot lines operational. Energy density 2.5x current lithium-ion. Cost parity expected by 2027.", tags: ["Technology", "Battery", "Supply Chain"] },
    ],
    heatmap: [
      { label: "EV Powertrain", val: "+28%", color: "rgba(16,185,129,0.3)" }, { label: "Autonomous", val: "+24%", color: "rgba(16,185,129,0.25)" },
      { label: "Connected Car", val: "+19%", color: "rgba(6,182,212,0.18)" }, { label: "Battery Tech", val: "+31%", color: "rgba(16,185,129,0.32)" },
      { label: "Software-Def", val: "+22%", color: "rgba(139,92,246,0.18)" }, { label: "Legacy ICE", val: "-12%", color: "rgba(239,68,68,0.15)" },
      { label: "Charging Infra", val: "+16%", color: "rgba(6,182,212,0.12)" }, { label: "Recycling", val: "+8%", color: "rgba(245,158,11,0.1)" },
    ],
    competitors: [
      { init: "B", name: "BYD", evt: "Revenue milestone", lvl: "High", lvlClass: "red" },
      { init: "T", name: "Tesla", evt: "FSD v13 rollout", lvl: "High", lvlClass: "red" },
      { init: "V", name: "VW Group", evt: "EV platform pivot", lvl: "Med", lvlClass: "amber" },
    ],
    radarCount: "Tracking 18",
    metrics: [
      { label: "Market Size", val: "$1.2T", color: "text-white" }, { label: "EV Share", val: "22.4%", color: "text-emerald-400" },
      { label: "VC Funding", val: "$41.2B", color: "text-cyan-400" }, { label: "Patent Filings", val: "12,847", color: "text-violet-400" },
    ],
    activity: [
      { title: "Competitor scan completed", detail: "2,184 sources • 87 insights" },
      { title: "Executive alert: BYD revenue", detail: "Sent to Strategy Team" },
      { title: "Regulatory tracker updated", detail: "NHTSA Level 4 framework" },
    ],
  },
  pharma: {
    label: "SECTOR: PHARMA & LIFE SCIENCES", sources: "3,412 sources",
    stats: { signals: "621", signalsDelta: "▲ 31%", alerts: "9", alertsDelta: "▲ 4", competitors: "22", compDelta: "6 active", confidence: "98.1%" },
    chartTag: "AI-Driven Drug Discovery", chartLeg1: "R&D Spend", chartVal: "$248B", chartDelta: "▲ 8.4%",
    insightTitle: "AI Accelerating Pipeline Velocity",
    insightDesc: "AI-designed molecules reaching Phase II 40% faster than traditional discovery. GLP-1 class generating $47B+ annually. Biosimilar competition intensifying across all major therapeutic areas.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "45min ago", title: "Novo Nordisk obesity drug Phase III results exceed expectations — $120B market impact", desc: "CagriSema shows 25.3% weight loss vs. 15.2% for semaglutide alone. Patent cliff implications for competitors. Market cap shift of $45B expected.", tags: ["Clinical Trial", "GLP-1", "Market Impact"] },
      { level: "MEDIUM", lvlClass: "amber", time: "4h ago", title: "FDA accelerates AI-generated drug candidate review pathway", desc: "New regulatory framework reduces IND review time by 60% for AI-validated compounds. Benefits Recursion, Insilico, and Isomorphic Labs.", tags: ["Regulatory", "AI/ML", "FDA"] },
      { level: "INNOVATION", lvlClass: "emerald", time: "12h ago", title: "DeepMind AlphaFold 3 achieves near-perfect protein-ligand binding prediction", desc: "Accuracy breakthrough reduces wet lab validation cycles from months to days. Pharma R&D productivity expected to improve 3-5x over next 3 years.", tags: ["Technology", "AI", "R&D"] },
    ],
    heatmap: [
      { label: "GLP-1 / Obesity", val: "+47%", color: "rgba(16,185,129,0.4)" }, { label: "AI Drug Disc.", val: "+38%", color: "rgba(16,185,129,0.32)" },
      { label: "Gene Therapy", val: "+22%", color: "rgba(6,182,212,0.2)" }, { label: "Biosimilars", val: "+18%", color: "rgba(6,182,212,0.15)" },
      { label: "Oncology", val: "+12%", color: "rgba(139,92,246,0.12)" }, { label: "Rare Disease", val: "+9%", color: "rgba(245,158,11,0.1)" },
      { label: "Cell Therapy", val: "+15%", color: "rgba(139,92,246,0.14)" }, { label: "Small Molecule", val: "-4%", color: "rgba(239,68,68,0.08)" },
    ],
    competitors: [
      { init: "N", name: "Novo Nordisk", evt: "Phase III results", lvl: "High", lvlClass: "red" },
      { init: "L", name: "Eli Lilly", evt: "Pricing pressure", lvl: "High", lvlClass: "red" },
      { init: "R", name: "Roche", evt: "AI partnership", lvl: "Med", lvlClass: "amber" },
    ],
    radarCount: "Tracking 22",
    metrics: [
      { label: "R&D Spend", val: "$248B", color: "text-white" }, { label: "AI Pipeline", val: "284 trials", color: "text-emerald-400" },
      { label: "M&A Volume", val: "$87.6B", color: "text-cyan-400" }, { label: "Patent Expiry", val: "$142B at risk", color: "text-red-400" },
    ],
    activity: [
      { title: "Clinical trial scan completed", detail: "3,412 sources • 124 insights" },
      { title: "Alert: Novo Nordisk Phase III", detail: "Sent to Executive Board" },
      { title: "Patent landscape updated", detail: "GLP-1 class expiry analysis" },
    ],
  },
  energy: {
    label: "SECTOR: ENERGY & UTILITIES", sources: "1,893 sources",
    stats: { signals: "445", signalsDelta: "▲ 12%", alerts: "8", alertsDelta: "▲ 2", competitors: "15", compDelta: "3 active", confidence: "97.2%" },
    chartTag: "Clean Energy Transition", chartLeg1: "Investment Flow", chartVal: "$1.8T", chartDelta: "▲ 17.1%",
    insightTitle: "Clean Energy Investment Surpasses Fossil Fuels",
    insightDesc: "Global clean energy investment hit $1.8T, exceeding fossil fuel capex for first time. Grid-scale battery storage costs down 40% in 2 years. Nuclear renaissance gaining momentum across 12 countries.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "3h ago", title: "US DOE approves $6.8B in nuclear SMR loan guarantees — sector catalyst", desc: "NuScale, TerraPower, and X-energy positioned to benefit. First commercial deployments targeted 2028.", tags: ["Policy", "Nuclear", "Investment"] },
      { level: "MEDIUM", lvlClass: "amber", time: "7h ago", title: "OPEC+ signals extended production cuts through Q2 2026", desc: "Oil price floor maintained at $75-85/bbl. Accelerates economic case for renewables.", tags: ["Market", "OPEC", "Pricing"] },
      { level: "INNOVATION", lvlClass: "emerald", time: "1d ago", title: "First commercial fusion net energy milestone — Commonwealth Fusion", desc: "SPARC tokamak achieves Q>2 in sustained operation. Commercial fusion timeline moves to 2032-2035.", tags: ["Technology", "Fusion", "Breakthrough"] },
    ],
    heatmap: [
      { label: "Solar", val: "+32%", color: "rgba(16,185,129,0.3)" }, { label: "Battery", val: "+28%", color: "rgba(16,185,129,0.25)" },
      { label: "Nuclear SMR", val: "+45%", color: "rgba(16,185,129,0.38)" }, { label: "Wind", val: "+14%", color: "rgba(6,182,212,0.12)" },
      { label: "Hydrogen", val: "+21%", color: "rgba(139,92,246,0.18)" }, { label: "Coal", val: "-18%", color: "rgba(239,68,68,0.18)" },
      { label: "Grid Tech", val: "+19%", color: "rgba(6,182,212,0.15)" }, { label: "Carbon Cap.", val: "+11%", color: "rgba(245,158,11,0.1)" },
    ],
    competitors: [
      { init: "N", name: "NextEra", evt: "Capacity expansion", lvl: "High", lvlClass: "red" },
      { init: "E", name: "Enel", evt: "Grid investment", lvl: "Med", lvlClass: "amber" },
      { init: "O", name: "Ørsted", evt: "Offshore wind delay", lvl: "Low", lvlClass: "blue" },
    ],
    radarCount: "Tracking 15",
    metrics: [
      { label: "Clean Invest.", val: "$1.8T", color: "text-white" }, { label: "Solar LCOE", val: "$24/MWh", color: "text-emerald-400" },
      { label: "Storage Deploy", val: "89 GWh", color: "text-cyan-400" }, { label: "Carbon Price", val: "$68/ton", color: "text-amber-400" },
    ],
    activity: [
      { title: "Policy scan completed", detail: "1,893 sources • 56 insights" },
      { title: "Nuclear report generated", detail: "SMR Opportunity Assessment" },
      { title: "Priority signal detected", detail: "DOE loan guarantee approval" },
    ],
  },
  finance: {
    label: "SECTOR: BANKING & FINANCE", sources: "2,651 sources",
    stats: { signals: "478", signalsDelta: "▲ 15%", alerts: "13", alertsDelta: "▲ 6", competitors: "20", compDelta: "5 active", confidence: "98.3%" },
    chartTag: "Digital Banking & Fintech", chartLeg1: "Market Value", chartVal: "$8.7T", chartDelta: "▲ 9.8%",
    insightTitle: "Embedded Finance Reshaping Banking",
    insightDesc: "Embedded finance projected to reach $7.2T by 2030. BaaS platforms enabling non-banks to offer financial products. Traditional banks accelerating API-first transformation — cost-to-serve declining 35%.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "1h ago", title: "Basel IV implementation timeline accelerated — capital impact $280B globally", desc: "BCBS confirms Q1 2026 enforcement. Output floor provisions increase risk-weighted assets by 15-25% for large banks.", tags: ["Regulatory", "Basel IV", "Capital"] },
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "4h ago", title: "JPMorgan deploys AI across all trading desks — $2.1B annual efficiency gain", desc: "Full-stack AI integration from risk pricing to execution. 4,200 quant analyst roles being restructured.", tags: ["Competitor", "AI/ML", "Trading"] },
      { level: "MEDIUM", lvlClass: "amber", time: "8h ago", title: "Central bank digital currency trials expand to 28 countries", desc: "ECB digital euro pilot reaches 50M users. Cross-border CBDC corridors being tested.", tags: ["CBDC", "Payments", "Infrastructure"] },
    ],
    heatmap: [
      { label: "Embedded Fin", val: "+34%", color: "rgba(16,185,129,0.3)" }, { label: "AI in Banking", val: "+42%", color: "rgba(16,185,129,0.35)" },
      { label: "RegTech", val: "+26%", color: "rgba(6,182,212,0.22)" }, { label: "CBDC", val: "+31%", color: "rgba(139,92,246,0.25)" },
      { label: "Crypto/DeFi", val: "+18%", color: "rgba(245,158,11,0.15)" }, { label: "Branch Banking", val: "-8%", color: "rgba(239,68,68,0.1)" },
      { label: "BaaS", val: "+29%", color: "rgba(16,185,129,0.24)" }, { label: "Cybersecurity", val: "+22%", color: "rgba(6,182,212,0.18)" },
    ],
    competitors: [
      { init: "J", name: "JPMorgan", evt: "AI deployment", lvl: "High", lvlClass: "red" },
      { init: "G", name: "Goldman Sachs", evt: "Platform launch", lvl: "High", lvlClass: "red" },
      { init: "S", name: "Stripe", evt: "Banking license", lvl: "Med", lvlClass: "amber" },
    ],
    radarCount: "Tracking 20",
    metrics: [
      { label: "Sector AUM", val: "$8.7T", color: "text-white" }, { label: "Fintech Invest", val: "$51.4B", color: "text-emerald-400" },
      { label: "Reg Actions", val: "847", color: "text-amber-400" }, { label: "AI Adoption", val: "62%", color: "text-cyan-400" },
    ],
    activity: [
      { title: "Regulatory scan completed", detail: "2,651 sources • 78 insights" },
      { title: "Basel IV impact assessment", detail: "Sent to Risk Committee" },
      { title: "Competitor alert: JPMorgan AI", detail: "Full trading desk deployment" },
    ],
  },
  investment: {
    label: "SECTOR: INVESTMENT BANKING", sources: "1,972 sources",
    stats: { signals: "389", signalsDelta: "▲ 22%", alerts: "6", alertsDelta: "▲ 2", competitors: "14", compDelta: "3 active", confidence: "97.5%" },
    chartTag: "M&A & Capital Markets", chartLeg1: "Deal Volume", chartVal: "$3.4T", chartDelta: "▲ 28.5%",
    insightTitle: "M&A Super-Cycle Emerging",
    insightDesc: "Global M&A volume up 28.5% YoY driven by AI consolidation, PE dry powder ($2.6T), and cross-border deals. Technology sector accounts for 38% of deal value.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "30min ago", title: "Broadcom in advanced talks to acquire VMware rival — $40B+ deal", desc: "Consolidation in enterprise infrastructure accelerating. Antitrust review expected 12-18 months.", tags: ["M&A", "Technology", "Deal Flow"] },
      { level: "MEDIUM", lvlClass: "amber", time: "3h ago", title: "IPO window reopening — $12B in tech filings this quarter", desc: "Stripe, Databricks, and Canva preparing S-1 filings. Investor appetite recovering with AI narrative.", tags: ["IPO", "Capital Markets", "Tech"] },
      { level: "INNOVATION", lvlClass: "emerald", time: "6h ago", title: "Tokenized securities clearing pilot achieves T+0 settlement", desc: "DTCC and JPMorgan pilot reduces settlement risk to near-zero. Blockchain infrastructure spend accelerating.", tags: ["Technology", "Settlement", "Infrastructure"] },
    ],
    heatmap: [
      { label: "Tech M&A", val: "+38%", color: "rgba(16,185,129,0.32)" }, { label: "PE Activity", val: "+24%", color: "rgba(16,185,129,0.2)" },
      { label: "IPO Market", val: "+45%", color: "rgba(16,185,129,0.38)" }, { label: "Debt Capital", val: "+18%", color: "rgba(6,182,212,0.15)" },
      { label: "Advisory", val: "+22%", color: "rgba(139,92,246,0.18)" }, { label: "SPACs", val: "-32%", color: "rgba(239,68,68,0.22)" },
      { label: "Cross-Border", val: "+15%", color: "rgba(6,182,212,0.12)" }, { label: "Restructuring", val: "+9%", color: "rgba(245,158,11,0.1)" },
    ],
    competitors: [
      { init: "G", name: "Goldman Sachs", evt: "AI trading desk", lvl: "High", lvlClass: "red" },
      { init: "M", name: "Morgan Stanley", evt: "Wealth M&A", lvl: "Med", lvlClass: "amber" },
      { init: "L", name: "Lazard", evt: "Advisory win", lvl: "Low", lvlClass: "blue" },
    ],
    radarCount: "Tracking 14",
    metrics: [
      { label: "Deal Volume", val: "$3.4T", color: "text-white" }, { label: "PE Dry Powder", val: "$2.6T", color: "text-emerald-400" },
      { label: "IPO Pipeline", val: "$87B", color: "text-cyan-400" }, { label: "Advisory Fees", val: "$48.2B", color: "text-violet-400" },
    ],
    activity: [
      { title: "Deal pipeline scan completed", detail: "1,972 sources • 64 insights" },
      { title: "M&A target list refreshed", detail: "Technology sector focus" },
      { title: "IPO readiness report", detail: "Q1 2025 window analysis" },
    ],
  },
  defense: {
    label: "SECTOR: DEFENSE & AEROSPACE", sources: "1,548 sources",
    stats: { signals: "298", signalsDelta: "▲ 27%", alerts: "10", alertsDelta: "▲ 4", competitors: "9", compDelta: "2 active", confidence: "96.4%" },
    chartTag: "Defense Modernization", chartLeg1: "Budget Allocation", chartVal: "$916B", chartDelta: "▲ 6.8%",
    insightTitle: "Autonomous Systems Driving Budget Reallocation",
    insightDesc: "NATO defense budgets hitting 2.5% GDP targets. Autonomous drones and AI-enabled C4ISR systems consuming 34% of new procurement. Space defense emerging as critical category.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "2h ago", title: "Pentagon awards $18B autonomous drone swarm contract — Anduril & Shield AI", desc: "Collaborative Combat Aircraft program accelerating. Legacy prime contractors losing share to tech-defense startups. Timeline: initial operating capability 2027.", tags: ["Contract", "Autonomous", "Procurement"] },
      { level: "MEDIUM", lvlClass: "amber", time: "6h ago", title: "European Defence Industrial Strategy allocates €120B for sovereign capabilities", desc: "Focus on AI, space, and cyber. Joint procurement mandates creating new market opportunities. Timeline: 2025-2035 phased deployment.", tags: ["Policy", "EU", "Budget"] },
      { level: "INNOVATION", lvlClass: "emerald", time: "1d ago", title: "Quantum-resistant encryption standard adopted by Five Eyes alliance", desc: "CRYSTALS-Kyber mandated for all classified communications by 2027. Massive upgrade cycle for defense IT infrastructure. $12B market opportunity.", tags: ["Technology", "Quantum", "Cybersecurity"] },
    ],
    heatmap: [
      { label: "Autonomous", val: "+34%", color: "rgba(16,185,129,0.3)" }, { label: "Space Defense", val: "+42%", color: "rgba(16,185,129,0.35)" },
      { label: "Cyber/AI", val: "+28%", color: "rgba(6,182,212,0.22)" }, { label: "Hypersonic", val: "+22%", color: "rgba(139,92,246,0.18)" },
      { label: "Naval", val: "+8%", color: "rgba(245,158,11,0.1)" }, { label: "Legacy Air", val: "-5%", color: "rgba(239,68,68,0.08)" },
      { label: "Missile Def.", val: "+18%", color: "rgba(6,182,212,0.15)" }, { label: "EW/ISR", val: "+25%", color: "rgba(16,185,129,0.22)" },
    ],
    competitors: [
      { init: "A", name: "Anduril", evt: "Major contract win", lvl: "High", lvlClass: "red" },
      { init: "L", name: "Lockheed Martin", evt: "F-35 delays", lvl: "Med", lvlClass: "amber" },
      { init: "R", name: "RTX", evt: "Missile expansion", lvl: "Low", lvlClass: "blue" },
    ],
    radarCount: "Tracking 9",
    metrics: [
      { label: "Global Budget", val: "$916B", color: "text-white" }, { label: "AI Alloc.", val: "$24.7B", color: "text-emerald-400" },
      { label: "Contract Pipe", val: "$142B", color: "text-cyan-400" }, { label: "Startup Inv.", val: "$8.9B", color: "text-violet-400" },
    ],
    activity: [
      { title: "Procurement scan completed", detail: "1,548 sources • 38 insights" },
      { title: "Contract tracker updated", detail: "Pentagon autonomous programs" },
      { title: "Geopolitical brief generated", detail: "NATO budget compliance" },
    ],
  },
  telecom: {
    label: "SECTOR: TELECOM", sources: "1,321 sources",
    stats: { signals: "267", signalsDelta: "▲ 9%", alerts: "5", alertsDelta: "▲ 1", competitors: "11", compDelta: "2 active", confidence: "97.6%" },
    chartTag: "5G & Network Infrastructure", chartLeg1: "Capex Spend", chartVal: "$342B", chartDelta: "▲ 5.4%",
    insightTitle: "AI RAN and Network-as-a-Service Accelerating",
    insightDesc: "Open RAN deployments growing 45% YoY. AI-driven network optimization reducing opex 20-30%. Private 5G enterprise market reaching $12B. Satellite-terrestrial convergence emerging.",
    signals: [
      { level: "HIGH_PRIORITY", lvlClass: "red", time: "3h ago", title: "T-Mobile & SpaceX achieve direct-to-cell satellite service — industry disruption", desc: "Universal coverage without ground infrastructure. Eliminates rural coverage economics barrier. Existential threat to tower companies and MVNOs.", tags: ["Competitor", "Satellite", "Disruption"] },
      { level: "MEDIUM", lvlClass: "amber", time: "5h ago", title: "EU mandates Open RAN for all publicly funded network builds", desc: "Policy shift away from single-vendor dependency. Benefits Mavenir, Rakuten Symphony, and Dell. Nokia/Ericsson revenue at risk in public contracts.", tags: ["Regulatory", "Open RAN", "Policy"] },
      { level: "INNOVATION", lvlClass: "emerald", time: "10h ago", title: "6G research consortium achieves 1Tbps in lab conditions", desc: "Samsung, NTT, and Nokia demonstrating sub-THz frequencies. Commercial 6G deployment expected 2030-2032.", tags: ["Technology", "6G", "Research"] },
    ],
    heatmap: [
      { label: "Open RAN", val: "+45%", color: "rgba(16,185,129,0.38)" }, { label: "AI/ML Ops", val: "+32%", color: "rgba(16,185,129,0.28)" },
      { label: "Private 5G", val: "+28%", color: "rgba(6,182,212,0.22)" }, { label: "Satellite", val: "+52%", color: "rgba(16,185,129,0.42)" },
      { label: "Edge Compute", val: "+18%", color: "rgba(139,92,246,0.15)" }, { label: "Legacy 4G", val: "-6%", color: "rgba(239,68,68,0.08)" },
      { label: "NaaS", val: "+24%", color: "rgba(6,182,212,0.18)" }, { label: "Fiber", val: "+11%", color: "rgba(245,158,11,0.1)" },
    ],
    competitors: [
      { init: "S", name: "SpaceX/Starlink", evt: "Direct-to-cell", lvl: "High", lvlClass: "red" },
      { init: "T", name: "T-Mobile", evt: "Satellite partnership", lvl: "Med", lvlClass: "amber" },
      { init: "R", name: "Rakuten", evt: "Open RAN export", lvl: "Low", lvlClass: "blue" },
    ],
    radarCount: "Tracking 11",
    metrics: [
      { label: "Capex Spend", val: "$342B", color: "text-white" }, { label: "5G Subs", val: "2.1B", color: "text-emerald-400" },
      { label: "Open RAN Rev", val: "$18.4B", color: "text-cyan-400" }, { label: "Satellite Rev", val: "$9.2B", color: "text-violet-400" },
    ],
    activity: [
      { title: "Network scan completed", detail: "1,321 sources • 31 insights" },
      { title: "Satellite disruption report", detail: "Direct-to-cell impact analysis" },
      { title: "Open RAN tracker updated", detail: "EU mandate implications" },
    ],
  },
};

export const industryChatData = {
  manufacturing: {
    subline: "Ask anything about your manufacturing intelligence landscape",
    userQ1: "What are the biggest competitive threats in industrial automation right now?",
    userQ2: "Deep dive on the Siemens threat — what should we do about it?",
    placeholder: "Ask about competitive landscape, market trends, or strategic recommendations...",
    sug1: "Summarize today's top signals", sug2: "Compare us vs top competitor", sug3: "Generate board-ready brief",
    threats: [
      { title: "Siemens AI-native factory OS", desc: "Platform play integrating digital twin + predictive maintenance. Market share risk: 12-18%." },
      { title: "ABB acquisition strategy", desc: "Rumored $4.2B acquisition of robotics startup, expanding autonomous operations capability." },
      { title: "Chinese robotics price disruption", desc: "KUKA/Midea achieving 40% cost advantage with comparable quality. Growing APAC share rapidly." },
    ],
    sourcesCount: 12, deepDivePoints: 47,
    assessment: "Siemens is consolidating the factory-floor stack. Their approach bundles digital twin, edge AI, and predictive maintenance into one subscription platform — directly competing with best-of-breed solutions.",
    recs: [
      "Accelerate open-architecture positioning — interoperability is your moat vs. their walled garden",
      "Target Siemens' existing MindSphere customers showing churn signals (14 accounts flagged)",
      "Partner with Rockwell Automation on joint go-to-market — they face the same threat",
    ],
  },
  automotive: {
    subline: "Ask anything about your automotive intelligence landscape",
    userQ1: "How is BYD threatening our European market position?",
    userQ2: "What defensive strategy should we adopt for the EV transition?",
    placeholder: "Ask about EV competition, autonomous driving trends, or supply chain risks...",
    sug1: "Show BYD expansion timeline", sug2: "EV pricing pressure analysis", sug3: "Board brief on China risk",
    threats: [
      { title: "BYD's European pricing strategy", desc: "Undercutting incumbents by 30-40% on comparable EV specs. Market share growing 8% QoQ in EU." },
      { title: "Tesla FSD v13 autonomy lead", desc: "Full self-driving approaching L4 capability. Software revenue model disrupting traditional OEM economics." },
      { title: "Battery supply chain consolidation", desc: "CATL and BYD controlling 65% of global cell production. Vertical integration creating cost moats." },
    ],
    sourcesCount: 24, deepDivePoints: 63,
    assessment: "BYD is executing a three-pronged European strategy: aggressive pricing, local assembly announcements in Hungary and Turkey, and a brand repositioning campaign. Their vertical integration gives them 25% cost advantage at the battery level.",
    recs: [
      "Accelerate platform cost reduction — target $22K base price for compact EV by 2027",
      "Secure alternative battery supply: negotiate directly with CATL or invest in European gigafactory",
      "Lobby for EU tariff extension and origin-content requirements to slow Chinese imports",
    ],
  },
  pharma: {
    subline: "Ask anything about your pharma & life sciences intelligence landscape",
    userQ1: "What is the impact of Novo Nordisk Phase III results on our GLP-1 pipeline?",
    userQ2: "Should we pivot our obesity drug strategy based on CagriSema data?",
    placeholder: "Ask about clinical trials, drug pipeline risks, or regulatory developments...",
    sug1: "Patent cliff exposure analysis", sug2: "AI drug discovery pipeline", sug3: "FDA regulatory tracker",
    threats: [
      { title: "Novo Nordisk CagriSema results", desc: "25.3% weight loss in Phase III — sets new efficacy bar. Our pipeline candidate must exceed or differentiate." },
      { title: "Eli Lilly tirzepatide expansion", desc: "Aggressive label expansion into MASH, sleep apnea, and heart failure. Broadening addressable market 4x." },
      { title: "AI-first biotechs accelerating", desc: "Recursion and Isomorphic Labs cutting discovery timelines to 18 months. Disruptive to traditional R&D model." },
    ],
    sourcesCount: 31, deepDivePoints: 84,
    assessment: "CagriSema's 25.3% weight loss sets a new efficacy standard. Our GLP-1/GIP dual agonist shows 19.8% in Phase II — not competitive enough as monotherapy. Combination or differentiation strategy required.",
    recs: [
      "Accelerate combination trial with our oral GIPR modulator — differentiation on convenience + efficacy",
      "Explore acquisition of Carmot Therapeutics for their amylin analogue (adds 5-8% incremental weight loss)",
      "Pivot Phase III design to target cardiovascular outcomes — the next competitive frontier",
    ],
  },
  energy: {
    subline: "Ask anything about your energy & utilities intelligence landscape",
    userQ1: "How does the nuclear SMR loan guarantee affect our renewables portfolio?",
    userQ2: "Should we reallocate capital toward nuclear given the policy shift?",
    placeholder: "Ask about clean energy policy, grid modernization, or carbon market trends...",
    sug1: "Grid storage cost analysis", sug2: "Carbon credit price forecast", sug3: "Nuclear vs renewables brief",
    threats: [
      { title: "Nuclear SMR renaissance", desc: "$6.8B DOE loan guarantees shifting investment thesis. SMRs compete directly with gas peakers and baseload renewables." },
      { title: "Chinese solar module dumping", desc: "Module prices down 50% in 12 months. Margin compression across entire solar value chain. Tariff response uncertain." },
      { title: "Grid interconnection bottleneck", desc: "2,600 GW in US interconnection queues. Average wait time now 5+ years. Stranding project economics." },
    ],
    sourcesCount: 18, deepDivePoints: 52,
    assessment: "The nuclear SMR policy shift represents a credible long-term threat to baseload renewables + storage economics. However, SMR deployment timeline (2028+) gives you a 3-4 year window to lock in PPAs and grid connections.",
    recs: [
      "Accelerate grid interconnection for approved projects — first-mover advantage before queue reform",
      "Evaluate strategic minority stake in NuScale or X-energy to hedge portfolio",
      "Develop hybrid solar+storage+SMR proposals for utility RFPs — position as technology-agnostic partner",
    ],
  },
  finance: {
    subline: "Ask anything about your banking & finance intelligence landscape",
    userQ1: "How will JPMorgan's AI trading deployment affect our competitive position?",
    userQ2: "What is our best response to Basel IV capital requirements?",
    placeholder: "Ask about regulatory impact, fintech threats, or digital transformation trends...",
    sug1: "Basel IV capital impact model", sug2: "Digital banking benchmark", sug3: "AI readiness scorecard",
    threats: [
      { title: "JPMorgan full-stack AI trading", desc: "$2.1B efficiency gain from AI integration across all desks. 4,200 roles restructured. Setting pace for industry." },
      { title: "Basel IV capital floor impact", desc: "Risk-weighted assets increasing 15-25% for large banks. $280B global capital impact. Q1 2026 enforcement." },
      { title: "Stripe banking license ambitions", desc: "Full banking charter application signals embedded finance disruption at scale. SMB lending market at risk." },
    ],
    sourcesCount: 22, deepDivePoints: 58,
    assessment: "JPMorgan's AI deployment creates a two-speed banking industry. Their $2.1B efficiency gain translates to 40bps cost-to-serve advantage. Without equivalent AI transformation, mid-tier banks face structural margin compression.",
    recs: [
      "Fast-track AI deployment in credit risk and trade execution — target $500M efficiency gain by 2026",
      "Partner with AI infrastructure provider (not build in-house) to close the 18-month gap",
      "Preemptively optimize RWA under Basel IV — divest low-return, high-capital portfolios now",
    ],
  },
  investment: {
    subline: "Ask anything about your investment banking intelligence landscape",
    userQ1: "What are the hottest M&A targets in the AI consolidation wave?",
    userQ2: "How should we position for the IPO window reopening?",
    placeholder: "Ask about deal pipeline, capital markets outlook, or advisory opportunities...",
    sug1: "Top 10 M&A targets by sector", sug2: "IPO readiness tracker", sug3: "PE dry powder deployment",
    threats: [
      { title: "AI infrastructure M&A wave", desc: "$40B+ in pending deals. Broadcom, Oracle, and Salesforce competing for targets. Advisory fee pool: $800M." },
      { title: "Goldman Sachs AI-powered deal origination", desc: "Automated pipeline scoring identifying targets 3x faster. Winning mandates before competitors engage." },
      { title: "Direct lending bypassing banks", desc: "Private credit funds providing $180B in acquisition financing. Disintermediating leveraged finance desks." },
    ],
    sourcesCount: 16, deepDivePoints: 41,
    assessment: "The IPO window is reopening with $87B in tech filings. Stripe, Databricks, and Canva are headline deals. Historical pattern suggests 60-day window before market rotation — timing is critical for mandate capture.",
    recs: [
      "Immediately engage Stripe CFO team — they're selecting lead underwriters this quarter",
      "Build AI-sector specialization unit: hire 3 senior analysts from tech banking",
      "Launch proprietary M&A target scoring model to match Goldman's AI-powered origination",
    ],
  },
  defense: {
    subline: "Ask anything about your defense & aerospace intelligence landscape",
    userQ1: "How does Anduril's contract win change the competitive dynamics?",
    userQ2: "Should we pivot toward autonomous systems or double down on traditional platforms?",
    placeholder: "Ask about procurement trends, geopolitical risks, or technology shifts...",
    sug1: "Pentagon budget allocation map", sug2: "Autonomous systems pipeline", sug3: "NATO capability gap brief",
    threats: [
      { title: "Anduril's $18B drone swarm contract", desc: "Tech-defense startup winning programs traditionally held by primes. Collaborative Combat Aircraft accelerating." },
      { title: "European defense sovereignty push", desc: "€120B EU defense strategy prioritizing European manufacturers. US defense exports at risk in NATO markets." },
      { title: "Quantum-resistant encryption mandate", desc: "Five Eyes requiring CRYSTALS-Kyber by 2027. $12B infrastructure upgrade cycle. First-movers gain certification advantage." },
    ],
    sourcesCount: 14, deepDivePoints: 38,
    assessment: "Anduril is redefining defense procurement. Their software-defined approach delivers autonomous drone swarms at 1/10th the cost of traditional platforms. Pentagon is explicitly shifting budget from legacy programs to CCA.",
    recs: [
      "Acquire or partner with autonomy-first defense startup — capability gap is widening",
      "Reposition legacy platform programs as 'manned-unmanned teaming' to retain budget allocation",
      "Invest in quantum-resistant encryption certification — early compliance becomes competitive advantage",
    ],
  },
  telecom: {
    subline: "Ask anything about your telecom intelligence landscape",
    userQ1: "How does the SpaceX direct-to-cell service threaten our network strategy?",
    userQ2: "Should we invest in satellite partnerships or accelerate Open RAN?",
    placeholder: "Ask about 5G infrastructure, spectrum strategy, or network economics...",
    sug1: "Open RAN vendor comparison", sug2: "Satellite disruption timeline", sug3: "Private 5G opportunity map",
    threats: [
      { title: "SpaceX direct-to-cell satellite service", desc: "Universal coverage without ground infrastructure. Existential threat to tower economics and rural coverage business case." },
      { title: "EU Open RAN mandate", desc: "Policy shift away from single-vendor dependency. Existing Nokia/Ericsson contracts at risk for publicly funded builds." },
      { title: "Hyperscaler edge network expansion", desc: "AWS, Azure, and GCP deploying compute at cell tower level. Disintermediating telco edge revenue." },
    ],
    sourcesCount: 19, deepDivePoints: 44,
    assessment: "SpaceX direct-to-cell eliminates the rural coverage business case. T-Mobile partnership validates the model. Within 3 years, satellite will provide baseline connectivity everywhere — ground networks must differentiate on speed and capacity.",
    recs: [
      "Negotiate satellite partnership immediately — first-mover telco in each market captures subscriber loyalty",
      "Accelerate urban densification and indoor coverage — areas where satellite cannot compete",
      "Launch enterprise private 5G offering to diversify revenue away from consumer coverage economics",
    ],
  },
};
