import {
    BookOpen, BarChart3, Telescope, Headphones, Lightbulb,
    Shield, Server, Brain, Eye, Leaf, FileSearch, Gauge, Layers,
    Monitor, Calculator, Compass, Users, ArrowRight,
    Cpu, Database, Lock, KeyRound, Cloud, WifiOff, Network, Boxes, Sparkles, ScanEye, Zap,
    FileText, Award, ShieldCheck, Activity, HeartHandshake, ExternalLink,
    Scale, ScrollText, Binary, RadioTower,
    Landmark, Plane, Building2, Factory, TrendingUp, Settings, Microscope, ClipboardCheck,
    Info, Target, UserCheck, Trophy, Globe, Bot, Coins, FlaskConical, Code2, Briefcase,
    Building, Handshake, Mail, ChevronRight, Menu, X,
    Heart
} from "lucide-react";

const ICON_MAP = {
    "book-open": BookOpen,
    "bar-chart-3": BarChart3,
    "telescope": Telescope,
    "headphones": Headphones,
    "lightbulb": Lightbulb,
    "shield": Shield,
    "server": Server,
    "brain": Brain,
    "eye": Eye,
    "leaf": Leaf,
    "file-search": FileSearch,
    "gauge": Gauge,
    "layers": Layers,
    "monitor": Monitor,
    "calculator": Calculator,
    "compass": Compass,
    "users": Users,
    "arrow-right": ArrowRight,
    "cpu": Cpu,
    "database": Database,
    "lock": Lock,
    "key-round": KeyRound,
    "cloud": Cloud,
    "wifi-off": WifiOff,
    "network": Network,
    "boxes": Boxes,
    "sparkles": Sparkles,
    "scan-eye": ScanEye,
    "zap": Zap,
    "file-text": FileText,
    "award": Award,
    "shield-check": ShieldCheck,
    "activity": Activity,
    "heart-handshake": HeartHandshake,
    "external-link": ExternalLink,
    "scale": Scale,
    "scroll-text": ScrollText,
    "binary": Binary,
    "radio-tower": RadioTower,
    "landmark": Landmark,
    "plane": Plane,
    "building-2": Building2,
    "factory": Factory,
    "trending-up": TrendingUp,
    "settings": Settings,
    "microscope": Microscope,
    "clipboard-check": ClipboardCheck,
    "info": Info,
    "target": Target,
    "user-check": UserCheck,
    "trophy": Trophy,
    "globe": Globe,
    "bot": Bot,
    "coins": Coins,
    "flask-conical": FlaskConical,
    "code-2": Code2,
    "briefcase": Briefcase,
    "building": Building,
    "handshake": Handshake,
    "mail": Mail,
    "chevron-right": ChevronRight,
    "menu": Menu,
    "close": X,
    "heart": Heart,
};

export default function Icon({ name, className, style }) {
    const LucideIcon = ICON_MAP[name];
    if (!LucideIcon) return null;
    return <LucideIcon className={className} style={style} />;
}
