import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

const impactLabels = {
  efficiency: "Efficiency",
  downtime: "Downtime",
  dataAccuracy: "Data Accuracy",
  costSavings: "Cost Savings",
  diagnosisAccuracy: "Diagnosis",
  complianceScore: "Compliance",
  processingTime: "Processing",
  riskReduction: "Risk Reduction",
  decisionSpeed: "Decision Speed",
  accuracyImprovement: "Accuracy",
  riskDetection: "Risk Detection",
  timesSaved: "Time Saved",
  privacyCompliance: "Privacy",
  customerInsights: "Insights",
  revenueGrowth: "Revenue",
  auditReadiness: "Audit Ready",
  visibilityImprovement: "Visibility",
  delayReduction: "Delays",
  costOptimization: "Cost Savings",
  customerSatisfaction: "Satisfaction",
  securityCompliance: "Security",
  analysisSpeed: "Analysis",
  threatDetection: "Threat Detection",
  missionReadiness: "Readiness",
  responseTime: "Response Time",
  winRate: "Win Rate",
  complianceAccuracy: "Compliance",
  costReduction: "Cost Reduction",
  dataIntegration: "Integration",
  complianceTime: "Compliance Time",
  safetyDetection: "Safety",
  approvalAcceleration: "Approval",
  capacityOptimization: "Capacity",
  patientOutcomes: "Patient Outcomes",
  resourceEfficiency: "Efficiency",
  safetyPrediction: "Safety",
  assessmentTime: "Assessment",
  complianceAutomation: "Compliance",
  shortageReduction: "Shortages",
  counterfeitDetection: "Authentication",
  conflictResolution: "Conflict Resolution",
  capacityIncrease: "Capacity",
  safetyImprovement: "Safety",
  orUtilization: "OR Utilization",
  staffOptimization: "Staff",
  patientFlow: "Patient Flow",
  reviewSpeed: "Review Speed",
  dealVelocity: "Deal Speed",
  anomalyDetection: "Anomaly Detection",
  autonomousOps: "Autonomous Ops",
  missionSuccess: "Mission Success",
  approvalTime: "Approval Time",
  documentationEfficiency: "Documentation",
  submissionAccuracy: "Submissions",
  patientRecruitment: "Patient Recruitment",
  diagnosis: "Diagnosis",
  compliance: "Compliance",
  processing: "Processing",
  integration: "Integration",
  submissionSpeed: "FDA Submissions",
  missionReadiness: "Mission Readiness",
  riskReduction: "Risk Reduction",
  diagnosisAccuracy: "Diagnosis",
  dataAccuracy: "Data Accuracy",
  complianceScore: "Compliance Score",
  dataIntegration: "Data Integration",
  complianceTime: "Compliance Time",
  patientRecruitment: "Recruitment",
};

export const getImpactEntries = (impact) => {
  return Object.entries(impact).map(([key, value]) => ({
    label: impactLabels[key] || key,
    value,
  }));
};