"use client";

export default function TermsOfServiceContent() {
  return (
    <div className="legal-body">
      
      <h2 id="acceptance">1. Acceptance of Terms</h2>
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of Genovation&apos;s products and services 
        (collectively, the &quot;Services&quot;). By accessing, installing, or using the Services, you 
        (&quot;Customer,&quot; &quot;you,&quot; or &quot;your&quot;) agree to be bound by these Terms. 
        If you do not agree, you may not use the Services.
      </p>
      <p>
        If you are entering into these Terms on behalf of a company or other legal entity, you represent that 
        you have the authority to bind such entity to these Terms. In that case, &quot;you&quot; and &quot;your&quot; 
        will refer to that entity.
      </p>

      <h2 id="definitions">2. Definitions</h2>
      <p>
        <strong>&quot;Customer&quot;</strong> means the individual or entity that has entered into an agreement 
        with Genovation for use of the Services.
      </p>
      <p>
        <strong>&quot;Customer Data&quot;</strong> means all data, content, and materials provided by or on behalf 
        of Customer to the platform, including documents, databases, queries, and outputs generated by agents 
        operating on Customer Data.
      </p>
      <p>
        <strong>&quot;Platform&quot;</strong> means the Genovation software, including Mentis AgentOS, JUDGE 
        governance engine, CipherVault, and all associated components deployed within Customer&apos;s infrastructure.
      </p>
      <p>
        <strong>&quot;Authorized Users&quot;</strong> means individuals authorized by Customer to access and use 
        the Platform under the applicable license.
      </p>

      <h2 id="license">3. License & Access</h2>
      <p>
        Subject to these Terms and payment of applicable fees, Genovation grants Customer a non-exclusive, 
        non-transferable, non-sublicensable license to install, configure, and operate the Platform within 
        Customer&apos;s own infrastructure for the duration of the subscription term.
      </p>
      <p>
        The license is limited to the number of Authorized Users, agent instances, and deployment environments 
        specified in the applicable Order Form. Customer may not exceed these limits without prior written 
        authorization and payment of additional fees.
      </p>

      <h2 id="your-data">4. Your Data</h2>
      <div className="callout">
        <p>
          <strong>Your data is yours.</strong> Genovation does not access, collect, store, or process Customer Data. 
          The Platform operates entirely within your infrastructure. We have no technical ability to access your data, 
          and we claim no rights to it.
        </p>
      </div>
      <p>
        Customer retains all rights, title, and interest in and to Customer Data. No license to Customer Data is 
        granted to Genovation by virtue of these Terms. Customer is solely responsible for the legality, quality, 
        and integrity of Customer Data and the means by which it was obtained.
      </p>
      <p>
        Outputs generated by Mentis agents operating on Customer Data are Customer Data and belong exclusively to Customer.
      </p>

      <h2 id="responsibilities">5. Your Responsibilities</h2>
      <p>Customer agrees to:</p>
      <ul>
        <li>Use the Services in compliance with all applicable laws, regulations, and these Terms</li>
        <li>Maintain appropriate security measures for the infrastructure on which the Platform is deployed</li>
        <li>Ensure Authorized Users comply with these Terms and the Acceptable Use Policy</li>
        <li>Not reverse-engineer, decompile, disassemble, or attempt to derive the source code of the Platform</li>
        <li>Not sublicense, resell, or redistribute the Platform or access to it</li>
        <li>Promptly notify Genovation of any unauthorized access or security breach affecting the Platform</li>
      </ul>

      <h2 id="ip">6. Intellectual Property</h2>
      <p>
        Genovation retains all rights, title, and interest in the Platform, including all software, algorithms, 
        models, documentation, trademarks, and proprietary methodologies. These Terms do not transfer ownership 
        of any intellectual property.
      </p>
      <p>
        Customer retains all rights in Customer Data. Any feedback, suggestions, or improvement ideas provided by 
        Customer to Genovation may be used by Genovation to improve the Platform without obligation or compensation.
      </p>

      <h2 id="sla">7. Service Levels</h2>
      <p>
        The Platform is deployed on-premise within Customer&apos;s infrastructure. As such, uptime, performance, 
        and availability are primarily determined by Customer&apos;s infrastructure, not Genovation&apos;s. 
        Genovation&apos;s service level commitments, where applicable, are defined in the applicable Enterprise 
        Agreement or Order Form and pertain to software maintenance, support response times, and update delivery.
      </p>

      <h2 id="payment">8. Payment</h2>
      <p>
        Fees are specified in the applicable Order Form and are due in accordance with the payment terms set forth 
        therein. All fees are non-refundable except as expressly stated in the applicable agreement. Late payments 
        may accrue interest at the rate of 1.5% per month (or the maximum rate permitted by law, whichever is less).
      </p>

      <h2 id="warranty">9. Warranties & Disclaimers</h2>
      <p>
        Genovation warrants that the Platform will perform materially in accordance with its published documentation 
        during the subscription term. If the Platform fails to meet this warranty, Customer&apos;s exclusive remedy 
        is to receive corrections, updates, or workarounds, or, if Genovation cannot remedy the issue within a 
        reasonable period, termination of the affected subscription with a pro-rata refund.
      </p>
      <p>
        <strong>
          EXCEPT AS EXPRESSLY SET FORTH ABOVE, THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; 
          GENOVATION DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, 
          FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </strong>
      </p>

      <h2 id="liability">10. Limitation of Liability</h2>
      <p>
        <strong>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, GENOVATION&apos;S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR 
          RELATED TO THESE TERMS WILL NOT EXCEED THE AMOUNTS PAID BY CUSTOMER IN THE 12 MONTHS PRECEDING THE CLAIM.
        </strong>
      </p>
      <p>
        <strong>
          GENOVATION WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR 
          LOSS OF PROFITS, DATA, BUSINESS, OR GOODWILL, REGARDLESS OF THE THEORY OF LIABILITY.
        </strong>
      </p>
      <p>
        These limitations apply to the maximum extent permitted by applicable law and do not limit liability for 
        fraud, gross negligence, or willful misconduct.
      </p>

      <h2 id="indemnification">11. Indemnification</h2>
      <p>
        Genovation will defend Customer against third-party claims alleging that Customer&apos;s authorized use of 
        the Platform infringes a third party&apos;s intellectual property rights, and will indemnify Customer against 
        any resulting damages and costs.
      </p>
      <p>
        Customer will defend and indemnify Genovation against claims arising from Customer Data, Customer&apos;s use 
        of the Platform in violation of these Terms, or Customer&apos;s violation of applicable law.
      </p>

      <h2 id="term">12. Term & Termination</h2>
      <p>
        These Terms are effective as of the date Customer first accesses the Services and continue for the subscription 
        term specified in the applicable Order Form. Either party may terminate for material breach if the breach remains 
        uncured 30 days after written notice.
      </p>
      <p>
        Upon termination, Customer&apos;s license to use the Platform ceases. Customer Data remains within Customer&apos;s 
        infrastructure and is unaffected by termination. Genovation has no obligation to delete Customer Data (because 
        Genovation does not hold it).
      </p>

      <h2 id="general">13. General Provisions</h2>
      <p>
        <strong>Governing law:</strong> These Terms are governed by and construed in accordance with the laws of India, 
        without regard to conflict of law principles.
      </p>
      <p>
        <strong>Dispute resolution:</strong> Any disputes will be resolved through binding arbitration in accordance with 
        the Arbitration and Conciliation Act, 1996 (as amended), conducted in English. The seat of arbitration shall be 
        Kolkata, West Bengal, India. The courts of Kolkata shall have exclusive jurisdiction over any matters not subject 
        to arbitration.
      </p>
      <p>
        <strong>Assignment:</strong> Customer may not assign these Terms without Genovation Technological Solutions Pvt 
        Ltd&apos;s prior written consent. Genovation may assign in connection with a merger or sale of substantially all assets.
      </p>
      <p>
        <strong>Severability:</strong> If any provision is held unenforceable, the remaining provisions continue in full force.
      </p>
      <p>
        <strong>Entire agreement:</strong> These Terms, together with any applicable Order Form and Enterprise Agreement, 
        constitute the entire agreement between the parties regarding the subject matter hereof.
      </p>
      <p>
        <strong>Contact:</strong> <a href="mailto:legal@genovation.ai">legal@genovation.ai</a><br />
        Genovation Technological Solutions Pvt Ltd<br />
        Registered Office: Kolkata, West Bengal, India
      </p>

    </div>
  );
}